site_name: My First Doc
repo_url: https://github.com/felipesantos2/python-projects
repo_name: python-projects
edit_uri: https://github.com/felipesantos2/python-projects/tree/main

theme:
  name: material
  language: pt-BR
  logo: https://avatars.githubusercontent.com/u/583231?v=4